### PR TITLE
Improve readability of HOM test cases

### PR DESCRIPTION
**Pull request by phihos**
Codeclimate complains about duplicated code in the HOM test cases. This is my attempt to reduce duplication and improve readability at the same time. 
Some of my changes might be opinionated. Please tell me what you think.

### CODE REVIEW

**Comment by phihos** [comment]
The issues codeclimate raised do not seem to be completely resolvable without sacrificing readability. I suggest setting both issues to wontfix.

**Comment by konradhalas** [comment]
To be honest I'm not sure is it a good move. I know that with your changes we decrease number of lines in final tests, but from my point of view readability does not improve, eg.:

- `aor_mutation()` is of course shorter than `operators.Mutation(operator=operators.ArithmeticOperatorReplacement, node=node)` but second options is a little more expressive and straight forward
- when I see `mutations = self.THREE_AOR_MUTATIONS_ON_SUBTRACTION` I have to immediately jump to `THREE_AOR_MUTATIONS_ON_SUBTRACTION` and check what it is - I like tests where you can limit number of "jumps" to understand whats going on

I also want to discuss here a few coding practices:

- I see that you're using `given/when/then` comments -  I love this structure, but in a whole project I was using just blank lines to separate given/when/then blocks and I think that we should stick to one approach
- I know that in `unittest` module assertion methods are camelCase but I think that our custom assertions should be properly named with underscore convention
- I'm not a huge fun of docstrings, especially when documentation is nearly equal to the name of  method - in such cases we can skip it

Of course it's just my thoughts and I'm open to discussion :)

**Comment by phihos** [comment]
> To be honest I'm not sure is it a good move. I know that with your changes we decrease number of lines in final tests, but from my point of view readability does not improve, eg.:

> * aor_mutation() is of course shorter than operators.Mutation(operator=operators.ArithmeticOperatorReplacement, node=node) but second options is a little more expressive and straight forward
> * when I see mutations = self.THREE_AOR_MUTATIONS_ON_SUBTRACTION I have to immediately jump to THREE_AOR_MUTATIONS_ON_SUBTRACTION and check what it is - I like tests where you can limit number of "jumps" to understand whats going on

I see the point in your approach. My testing approach is to "hide away" test data initialization into constants and functions and give them meaningful names. 
Of course ```aor_mutation()``` and  ```THREE_AOR_MUTATIONS_ON_SUBTRACTION``` does not say it all, but in my opinion it is enough to get the intent of the test without looking it up in the function/constant.

Another issue I see is that there is a lot of duplication. Should the ```operators.Mutation(...)``` signature change for some reason, a lot of lines need to be touched.

All in all your appraoch has the also valid point of keeping the test code as simple as possible. After hearing my arguments how do you decide? It is totally fine with me to adapt your approach.


> I see that you're using given/when/then comments - I love this structure, but in a whole project I was using just blank lines to separate given/when/then blocks and I think that we should stick to one approach

I like the explicit separation with comments a little bit more,  but I can also follow your approach. It is not that important to me ;-)

> I know that in unittest module assertion methods are camelCase but I think that our custom assertions should be properly named with underscore convention

I agree on that one. I did it out of pure habit, because I programmed with Java before. Using underscores is the better thing to do.

> I'm not a huge fun of docstrings, especially when documentation is nearly equal to the name of method - in such cases we can skip it

Then I will remove them.

What about the new custom assertions? I needed some mintues and some code reading to understand the meaning of the ```assertEquals``` lines. Is replacing them with custom assertion ok with you?

**Comment by AnnaSkupinska** [comment]
Hello,

I would like to note that I have been working on mutpy for some time to write a bachelor thesis. I can't work on an unstable version, and I am bounded by a deadline. I wish to know what are you going to do with mut.py, and when you're going to finish doing it. I know that you're not going to finish all your goals at once, so if your tasks last longer than I am able to join our works, I'll have to use an earlyier version of mut.py. 

I want to write documentation for mut.py - that includes writing comments.  I also wish to create and evaluate new mutation operators.

I hope you acquired email with my questions. In case of some technical failure I've decided to send you my questions once again via this comment section. As @konradhalas said that those questions should be answered in a joint chat.

For now I'll try writing comments o existing methods (I want to write a documentation for mut.py)

1) What are your goals with mut.py? I don't want to collide with your work.

2) How mutation operators are being choosen for nodes? I know that operators.py contains a class MutationOperator which mutates nodes in a loop in controller.MutationController.mutate_module.

3) Coverage is still not entirely understood for me, custom node transformers in particular - how can they detect, that a node was used in a test?

4) AbstractCoverageNodeTransformer has many methods with "visit"+node_class.__name__ which should be called by visit() method. I suppose used visit method is from base class, since there is no such method defined in AbstractCoverageNodeTransformer. These methods are either inject_before_visit or inject_inside_visit from AbstractCoverageNodeTransformer. What changes these two methods do to nodes?

5) Is there AST node documentation? I can't find a good one. I wish to make new mutation operators, but I need to know how exacly these nodes work, and how they are parsed into code.

6) In coverage.py there are NodeTransformers that are dependent of python version.
I think that these NodeTransformers are used to determine which nodes are used in tests. Two versions that are inheriting after the abstract are different in returned lists of ast nodes. Where it is possible to find ast nodes for python versions? I couldn't find satysfying ast documentation to explain that. Best one is on the official python site here: https://docs.python.org/3.6/library/ast.html

**Comment by phihos** [comment]
Hello Anna,

I already answered your questions via email at your Google mail account. You university mail server does not offer TLS so my mail provider refuses to communicate with it.

Regarding the "stableness": We keep the master branch in a stable condition at all times. But if you do not want to frequently merge changes from there then you can check out the latest tagged version (v0.5.1) and work from there. Since you are going to add new mutations and comments you should be fine.

Please tell me via email,that you have read this so I can delete our posts here. Conversations like this do not belong in a PR thread.

**Comment by konradhalas** [comment]
> All in all your appraoch has the also valid point of keeping the test code as simple as possible. After hearing my arguments how do you decide? It is totally fine with me to adapt your approach

It also nothing so important for me, so lets stick with your approach.

> I like the explicit separation with comments a little bit more, but I can also follow your approach. It is not that important to me ;-)

Great, so please remove them - this will be more consistent with whole codebase. 

> What about the new custom assertions? I needed some mintues and some code reading to understand the meaning of the assertEquals lines. Is replacing them with custom assertion ok with you?

Yes, it's definitely a good practice.

In conclusion:

- remove given/when/then comments
- remove unnecessary doscstrings
- change camelCase to underscore syntax

... and then we can merge it :) 🍾

**Comment by phihos** [comment]
Since my old MutPy Github fork is not available anymore, I made your suggested changes in this repo and pushed them to master directly.

**Pull request closed without merging**
